version: "3.7"

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
#    depends_on:
#      - pgsql
#      - nginx
    volumes:
      - ./:/var/www/html
    networks:
      - fnsc.dev

  nginx:
    container_name: nginx
    image: nginx:1.24-alpine-slim
    working_dir: /var/www/html
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fnsc.dev

  pgsql:
    container_name: pgsql
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    volumes:
      - gravite:/var/lib/postgresql/data
      - ./docker/pgsql/01_pgsql.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - fnsc.dev

volumes:
  gravite:

networks:
  fnsc.dev:
    driver: bridge
